// <auto-generated />
namespace VehicleManagementApp.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tbl_Requisition_Modified_IsHoldAdded_ForShowNotification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tbl_Requisition_Modified_IsHoldAdded_ForShowNotification));
        
        string IMigrationMetadata.Id
        {
            get { return "201811181730330_Tbl_Requisition_Modified_IsHoldAdded_ForShowNotification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
