//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VehicleManagementApp.com.onnorokomsms.api2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SendSmsSoap", Namespace="http://api.onnorokomsms.com/")]
    public partial class SendSms : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback OneToOneBulkOperationCompleted;
        
        private System.Threading.SendOrPostCallback OneToOneOperationCompleted;
        
        private System.Threading.SendOrPostCallback OneToManyOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeliveryStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMaskOperationCompleted;
        
        private System.Threading.SendOrPostCallback NumberSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SMSDeliveryStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCurrentBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllMaskOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SendSms() {
            this.Url = global::VehicleManagementApp.Properties.Settings.Default.VehicleManagementApp_com_onnorokomsms_api2_SendSms;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event OneToOneBulkCompletedEventHandler OneToOneBulkCompleted;
        
        /// <remarks/>
        public event OneToOneCompletedEventHandler OneToOneCompleted;
        
        /// <remarks/>
        public event OneToManyCompletedEventHandler OneToManyCompleted;
        
        /// <remarks/>
        public event DeliveryStatusCompletedEventHandler DeliveryStatusCompleted;
        
        /// <remarks/>
        public event GetBalanceCompletedEventHandler GetBalanceCompleted;
        
        /// <remarks/>
        public event GetMaskCompletedEventHandler GetMaskCompleted;
        
        /// <remarks/>
        public event NumberSmsCompletedEventHandler NumberSmsCompleted;
        
        /// <remarks/>
        public event ListSmsCompletedEventHandler ListSmsCompleted;
        
        /// <remarks/>
        public event SMSDeliveryStatusCompletedEventHandler SMSDeliveryStatusCompleted;
        
        /// <remarks/>
        public event GetCurrentBalanceCompletedEventHandler GetCurrentBalanceCompleted;
        
        /// <remarks/>
        public event GetAllMaskCompletedEventHandler GetAllMaskCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.onnorokomsms.com/OneToOneBulk", RequestNamespace="http://api.onnorokomsms.com/", ResponseNamespace="http://api.onnorokomsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OneToOneBulk(MessageHeader messageHeader, WsSms[] wsSmses) {
            object[] results = this.Invoke("OneToOneBulk", new object[] {
                        messageHeader,
                        wsSmses});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OneToOneBulkAsync(MessageHeader messageHeader, WsSms[] wsSmses) {
            this.OneToOneBulkAsync(messageHeader, wsSmses, null);
        }
        
        /// <remarks/>
        public void OneToOneBulkAsync(MessageHeader messageHeader, WsSms[] wsSmses, object userState) {
            if ((this.OneToOneBulkOperationCompleted == null)) {
                this.OneToOneBulkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOneToOneBulkOperationCompleted);
            }
            this.InvokeAsync("OneToOneBulk", new object[] {
                        messageHeader,
                        wsSmses}, this.OneToOneBulkOperationCompleted, userState);
        }
        
        private void OnOneToOneBulkOperationCompleted(object arg) {
            if ((this.OneToOneBulkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OneToOneBulkCompleted(this, new OneToOneBulkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.onnorokomsms.com/OneToOne", RequestNamespace="http://api.onnorokomsms.com/", ResponseNamespace="http://api.onnorokomsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OneToOne(string userName, string userPassword, string mobileNumber, string smsText, string type, string maskName, string campaignName) {
            object[] results = this.Invoke("OneToOne", new object[] {
                        userName,
                        userPassword,
                        mobileNumber,
                        smsText,
                        type,
                        maskName,
                        campaignName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OneToOneAsync(string userName, string userPassword, string mobileNumber, string smsText, string type, string maskName, string campaignName) {
            this.OneToOneAsync(userName, userPassword, mobileNumber, smsText, type, maskName, campaignName, null);
        }
        
        /// <remarks/>
        public void OneToOneAsync(string userName, string userPassword, string mobileNumber, string smsText, string type, string maskName, string campaignName, object userState) {
            if ((this.OneToOneOperationCompleted == null)) {
                this.OneToOneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOneToOneOperationCompleted);
            }
            this.InvokeAsync("OneToOne", new object[] {
                        userName,
                        userPassword,
                        mobileNumber,
                        smsText,
                        type,
                        maskName,
                        campaignName}, this.OneToOneOperationCompleted, userState);
        }
        
        private void OnOneToOneOperationCompleted(object arg) {
            if ((this.OneToOneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OneToOneCompleted(this, new OneToOneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.onnorokomsms.com/OneToMany", RequestNamespace="http://api.onnorokomsms.com/", ResponseNamespace="http://api.onnorokomsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OneToMany(string userName, string userPassword, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            object[] results = this.Invoke("OneToMany", new object[] {
                        userName,
                        userPassword,
                        messageText,
                        numberList,
                        smsType,
                        maskName,
                        campaignName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OneToManyAsync(string userName, string userPassword, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            this.OneToManyAsync(userName, userPassword, messageText, numberList, smsType, maskName, campaignName, null);
        }
        
        /// <remarks/>
        public void OneToManyAsync(string userName, string userPassword, string messageText, string numberList, string smsType, string maskName, string campaignName, object userState) {
            if ((this.OneToManyOperationCompleted == null)) {
                this.OneToManyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOneToManyOperationCompleted);
            }
            this.InvokeAsync("OneToMany", new object[] {
                        userName,
                        userPassword,
                        messageText,
                        numberList,
                        smsType,
                        maskName,
                        campaignName}, this.OneToManyOperationCompleted, userState);
        }
        
        private void OnOneToManyOperationCompleted(object arg) {
            if ((this.OneToManyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OneToManyCompleted(this, new OneToManyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.onnorokomsms.com/DeliveryStatus", RequestNamespace="http://api.onnorokomsms.com/", ResponseNamespace="http://api.onnorokomsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeliveryStatus(string userName, string userPassword, string responseId) {
            object[] results = this.Invoke("DeliveryStatus", new object[] {
                        userName,
                        userPassword,
                        responseId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeliveryStatusAsync(string userName, string userPassword, string responseId) {
            this.DeliveryStatusAsync(userName, userPassword, responseId, null);
        }
        
        /// <remarks/>
        public void DeliveryStatusAsync(string userName, string userPassword, string responseId, object userState) {
            if ((this.DeliveryStatusOperationCompleted == null)) {
                this.DeliveryStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeliveryStatusOperationCompleted);
            }
            this.InvokeAsync("DeliveryStatus", new object[] {
                        userName,
                        userPassword,
                        responseId}, this.DeliveryStatusOperationCompleted, userState);
        }
        
        private void OnDeliveryStatusOperationCompleted(object arg) {
            if ((this.DeliveryStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeliveryStatusCompleted(this, new DeliveryStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.onnorokomsms.com/GetBalance", RequestNamespace="http://api.onnorokomsms.com/", ResponseNamespace="http://api.onnorokomsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBalance(string userName, string userPassword) {
            object[] results = this.Invoke("GetBalance", new object[] {
                        userName,
                        userPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBalanceAsync(string userName, string userPassword) {
            this.GetBalanceAsync(userName, userPassword, null);
        }
        
        /// <remarks/>
        public void GetBalanceAsync(string userName, string userPassword, object userState) {
            if ((this.GetBalanceOperationCompleted == null)) {
                this.GetBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBalanceOperationCompleted);
            }
            this.InvokeAsync("GetBalance", new object[] {
                        userName,
                        userPassword}, this.GetBalanceOperationCompleted, userState);
        }
        
        private void OnGetBalanceOperationCompleted(object arg) {
            if ((this.GetBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBalanceCompleted(this, new GetBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.onnorokomsms.com/GetMask", RequestNamespace="http://api.onnorokomsms.com/", ResponseNamespace="http://api.onnorokomsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMask(string userName, string userPassword) {
            object[] results = this.Invoke("GetMask", new object[] {
                        userName,
                        userPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMaskAsync(string userName, string userPassword) {
            this.GetMaskAsync(userName, userPassword, null);
        }
        
        /// <remarks/>
        public void GetMaskAsync(string userName, string userPassword, object userState) {
            if ((this.GetMaskOperationCompleted == null)) {
                this.GetMaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMaskOperationCompleted);
            }
            this.InvokeAsync("GetMask", new object[] {
                        userName,
                        userPassword}, this.GetMaskOperationCompleted, userState);
        }
        
        private void OnGetMaskOperationCompleted(object arg) {
            if ((this.GetMaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMaskCompleted(this, new GetMaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.onnorokomsms.com/NumberSms", RequestNamespace="http://api.onnorokomsms.com/", ResponseNamespace="http://api.onnorokomsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NumberSms(string apiKey, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            object[] results = this.Invoke("NumberSms", new object[] {
                        apiKey,
                        messageText,
                        numberList,
                        smsType,
                        maskName,
                        campaignName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NumberSmsAsync(string apiKey, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            this.NumberSmsAsync(apiKey, messageText, numberList, smsType, maskName, campaignName, null);
        }
        
        /// <remarks/>
        public void NumberSmsAsync(string apiKey, string messageText, string numberList, string smsType, string maskName, string campaignName, object userState) {
            if ((this.NumberSmsOperationCompleted == null)) {
                this.NumberSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNumberSmsOperationCompleted);
            }
            this.InvokeAsync("NumberSms", new object[] {
                        apiKey,
                        messageText,
                        numberList,
                        smsType,
                        maskName,
                        campaignName}, this.NumberSmsOperationCompleted, userState);
        }
        
        private void OnNumberSmsOperationCompleted(object arg) {
            if ((this.NumberSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NumberSmsCompleted(this, new NumberSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.onnorokomsms.com/ListSms", RequestNamespace="http://api.onnorokomsms.com/", ResponseNamespace="http://api.onnorokomsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ListSms(string apiKey, WsSms[] wsSmses, string maskName, string campaignName) {
            object[] results = this.Invoke("ListSms", new object[] {
                        apiKey,
                        wsSmses,
                        maskName,
                        campaignName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListSmsAsync(string apiKey, WsSms[] wsSmses, string maskName, string campaignName) {
            this.ListSmsAsync(apiKey, wsSmses, maskName, campaignName, null);
        }
        
        /// <remarks/>
        public void ListSmsAsync(string apiKey, WsSms[] wsSmses, string maskName, string campaignName, object userState) {
            if ((this.ListSmsOperationCompleted == null)) {
                this.ListSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListSmsOperationCompleted);
            }
            this.InvokeAsync("ListSms", new object[] {
                        apiKey,
                        wsSmses,
                        maskName,
                        campaignName}, this.ListSmsOperationCompleted, userState);
        }
        
        private void OnListSmsOperationCompleted(object arg) {
            if ((this.ListSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListSmsCompleted(this, new ListSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.onnorokomsms.com/SMSDeliveryStatus", RequestNamespace="http://api.onnorokomsms.com/", ResponseNamespace="http://api.onnorokomsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SMSDeliveryStatus(string apiKey, string responseId) {
            object[] results = this.Invoke("SMSDeliveryStatus", new object[] {
                        apiKey,
                        responseId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SMSDeliveryStatusAsync(string apiKey, string responseId) {
            this.SMSDeliveryStatusAsync(apiKey, responseId, null);
        }
        
        /// <remarks/>
        public void SMSDeliveryStatusAsync(string apiKey, string responseId, object userState) {
            if ((this.SMSDeliveryStatusOperationCompleted == null)) {
                this.SMSDeliveryStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSMSDeliveryStatusOperationCompleted);
            }
            this.InvokeAsync("SMSDeliveryStatus", new object[] {
                        apiKey,
                        responseId}, this.SMSDeliveryStatusOperationCompleted, userState);
        }
        
        private void OnSMSDeliveryStatusOperationCompleted(object arg) {
            if ((this.SMSDeliveryStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SMSDeliveryStatusCompleted(this, new SMSDeliveryStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.onnorokomsms.com/GetCurrentBalance", RequestNamespace="http://api.onnorokomsms.com/", ResponseNamespace="http://api.onnorokomsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCurrentBalance(string apiKey) {
            object[] results = this.Invoke("GetCurrentBalance", new object[] {
                        apiKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCurrentBalanceAsync(string apiKey) {
            this.GetCurrentBalanceAsync(apiKey, null);
        }
        
        /// <remarks/>
        public void GetCurrentBalanceAsync(string apiKey, object userState) {
            if ((this.GetCurrentBalanceOperationCompleted == null)) {
                this.GetCurrentBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurrentBalanceOperationCompleted);
            }
            this.InvokeAsync("GetCurrentBalance", new object[] {
                        apiKey}, this.GetCurrentBalanceOperationCompleted, userState);
        }
        
        private void OnGetCurrentBalanceOperationCompleted(object arg) {
            if ((this.GetCurrentBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCurrentBalanceCompleted(this, new GetCurrentBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.onnorokomsms.com/GetAllMask", RequestNamespace="http://api.onnorokomsms.com/", ResponseNamespace="http://api.onnorokomsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAllMask(string apiKey) {
            object[] results = this.Invoke("GetAllMask", new object[] {
                        apiKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllMaskAsync(string apiKey) {
            this.GetAllMaskAsync(apiKey, null);
        }
        
        /// <remarks/>
        public void GetAllMaskAsync(string apiKey, object userState) {
            if ((this.GetAllMaskOperationCompleted == null)) {
                this.GetAllMaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllMaskOperationCompleted);
            }
            this.InvokeAsync("GetAllMask", new object[] {
                        apiKey}, this.GetAllMaskOperationCompleted, userState);
        }
        
        private void OnGetAllMaskOperationCompleted(object arg) {
            if ((this.GetAllMaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllMaskCompleted(this, new GetAllMaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class MessageHeader {
        
        private string userNameField;
        
        private string userPasswordField;
        
        private string marskTextField;
        
        private string campingNameField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserPassword {
            get {
                return this.userPasswordField;
            }
            set {
                this.userPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string MarskText {
            get {
                return this.marskTextField;
            }
            set {
                this.marskTextField = value;
            }
        }
        
        /// <remarks/>
        public string CampingName {
            get {
                return this.campingNameField;
            }
            set {
                this.campingNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class WsSms {
        
        private string mobileNumberField;
        
        private string smsTextField;
        
        private string typeField;
        
        /// <remarks/>
        public string MobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SmsText {
            get {
                return this.smsTextField;
            }
            set {
                this.smsTextField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void OneToOneBulkCompletedEventHandler(object sender, OneToOneBulkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OneToOneBulkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OneToOneBulkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void OneToOneCompletedEventHandler(object sender, OneToOneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OneToOneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OneToOneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void OneToManyCompletedEventHandler(object sender, OneToManyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OneToManyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OneToManyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeliveryStatusCompletedEventHandler(object sender, DeliveryStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeliveryStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeliveryStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetBalanceCompletedEventHandler(object sender, GetBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetMaskCompletedEventHandler(object sender, GetMaskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void NumberSmsCompletedEventHandler(object sender, NumberSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NumberSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NumberSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ListSmsCompletedEventHandler(object sender, ListSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SMSDeliveryStatusCompletedEventHandler(object sender, SMSDeliveryStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SMSDeliveryStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SMSDeliveryStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetCurrentBalanceCompletedEventHandler(object sender, GetCurrentBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCurrentBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCurrentBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAllMaskCompletedEventHandler(object sender, GetAllMaskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllMaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllMaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591